In [163]:
import numpy as np
import pandas  as pd

In [164]:
df=pd.read_csv("crocodile_dataset - crocodile_dataset.csv")

In [165]:
df.head()

,Observation ID,Common Name,Scientific Name,Family,Genus,Observed Length (m),Observed Weight (kg),Age Class,Sex,Date of Observation,Country/Region,Habitat Type,Conservation Status,Observer Name,Notes
0,1,Morelet's Crocodile,Crocodylus moreletii,Crocodylidae,Crocodylus,1.90,62.0,Adult,Male,31-03-2018,Belize,Swamps,Least Concern,Allison Hill,Cause bill scientist nation opportunity.
1,2,American Crocodile,Crocodylus acutus,Crocodylidae,Crocodylus,4.09,334.5,Adult,Male,28-01-2015,Venezuela,Mangroves,Vulnerable,Brandon Hall,Ago current practice nation determine operatio...
2,3,Orinoco Crocodile,Crocodylus intermedius,Crocodylidae,Crocodylus,1.08,118.2,Juvenile,Unknown,07-12-2010,Venezuela,Flooded Savannas,Critically Endangered,Melissa Peterson,Democratic shake bill here grow gas enough ana...
3,4,Morelet's Crocodile,Crocodylus moreletii,Crocodylidae,Crocodylus,2.42,90.4,Adult,Male,01-11-2019,Mexico,Rivers,Least Concern,Edward Fuller,Officer relate animal direction eye bag do.
4,5,Mugger Crocodile (Marsh Crocodile),Crocodylus palustris,Crocodylidae,Crocodylus,3.75,269.4,Adult,Unknown,15-07-2019,India,Rivers,Vulnerable,Donald Reid,Class great prove reduce raise author play mov...

In [166]:
df.isnull().sum()

Observation ID          0
Common Name             0
Scientific Name         0
Family                  0
Genus                   0
Observed Length (m)     0
Observed Weight (kg)    0
Age Class               0
Sex                     0
Date of Observation     0
Country/Region          0
Habitat Type            0
Conservation Status     0
Observer Name           0
Notes                   0
dtype: int64

In [167]:
df=df.drop(columns=["Notes","Observation ID","Date of Observation"])
df.head()

,Common Name,Scientific Name,Family,Genus,Observed Length (m),Observed Weight (kg),Age Class,Sex,Country/Region,Habitat Type,Conservation Status,Observer Name
0,Morelet's Crocodile,Crocodylus moreletii,Crocodylidae,Crocodylus,1.90,62.0,Adult,Male,Belize,Swamps,Least Concern,Allison Hill
1,American Crocodile,Crocodylus acutus,Crocodylidae,Crocodylus,4.09,334.5,Adult,Male,Venezuela,Mangroves,Vulnerable,Brandon Hall
2,Orinoco Crocodile,Crocodylus intermedius,Crocodylidae,Crocodylus,1.08,118.2,Juvenile,Unknown,Venezuela,Flooded Savannas,Critically Endangered,Melissa Peterson
3,Morelet's Crocodile,Crocodylus moreletii,Crocodylidae,Crocodylus,2.42,90.4,Adult,Male,Mexico,Rivers,Least Concern,Edward Fuller
4,Mugger Crocodile (Marsh Crocodile),Crocodylus palustris,Crocodylidae,Crocodylus,3.75,269.4,Adult,Unknown,India,Rivers,Vulnerable,Donald Reid

In [168]:
from sklearn.model_selection import train_test_split

In [169]:
x=df.drop(columns=["Conservation Status"])
y=df["Conservation Status"]

In [170]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [171]:
df.dtypes

Common Name              object
Scientific Name          object
Family                   object
Genus                    object
Observed Length (m)     float64
Observed Weight (kg)    float64
Age Class                object
Sex                      object
Country/Region           object
Habitat Type             object
Conservation Status      object
Observer Name            object
dtype: object

In [172]:
x_train["Age Class"].value_counts

<bound method IndexOpsMixin.value_counts of 29        Adult
535    Subadult
695    Subadult
557       Adult
836       Adult
         ...
106       Adult
270    Juvenile
860       Adult
435       Adult
102       Adult
Name: Age Class, Length: 800, dtype: object>

In [173]:
x_train.head(2)

,Common Name,Scientific Name,Family,Genus,Observed Length (m),Observed Weight (kg),Age Class,Sex,Country/Region,Habitat Type,Observer Name
29,Orinoco Crocodile,Crocodylus intermedius,Crocodylidae,Crocodylus,4.71,576.6,Adult,Female,Venezuela,Flooded Savannas,Jamie Adkins
535,Orinoco Crocodile,Crocodylus intermedius,Crocodylidae,Crocodylus,3.96,385.8,Subadult,Male,Venezuela,Large Rivers,Richard Lee

In [174]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler ,OrdinalEncoder ,OneHotEncoder

In [175]:
transformer=ColumnTransformer(transformers=[
    ("scalling",StandardScaler(),["Observed Length (m)","Observed Weight (kg)"]),
    ("Ordinal",OrdinalEncoder(categories=[["Adult","Juvenile","Subadult",'Hatchling']]),["Age Class"]),
    ("Onehot",OneHotEncoder(sparse_output=False, drop="first"),["Common Name","Scientific Name","Family","Genus","Sex","Country/Region","Habitat Type","Observer Name"])
    
],remainder="passthrough")

In [176]:
x_train_tf=transformer.fit_transform(x_train)
x_train_tf.shape

(800, 904)

In [178]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('scalling', StandardScaler(),
                                 ['Observed Length (m)',
                                  'Observed Weight (kg)']),
                                ('Ordinal',
                                 OrdinalEncoder(categories=[['Adult',
                                                             'Juvenile',
                                                             'Subadult',
                                                             'Hatchling']]),
                                 ['Age Class']),
                                ('Onehot',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['Common Name', 'Scientific Name', 'Family',
                                  'Genus', 'Sex', 'Country/Region',
                                  'Habitat Type', 'Observer Name'])])

In [60]:
print("----------------------------------------------------------------------------")

----------------------------------------------------------------------------

In [141]:
df2=pd.read_csv("crocodile_dataset - crocodile_dataset.csv")

In [142]:
df2.head()

,Observation ID,Common Name,Scientific Name,Family,Genus,Observed Length (m),Observed Weight (kg),Age Class,Sex,Date of Observation,Country/Region,Habitat Type,Conservation Status,Observer Name,Notes
0,1,Morelet's Crocodile,Crocodylus moreletii,Crocodylidae,Crocodylus,1.90,62.0,Adult,Male,31-03-2018,Belize,Swamps,Least Concern,Allison Hill,Cause bill scientist nation opportunity.
1,2,American Crocodile,Crocodylus acutus,Crocodylidae,Crocodylus,4.09,334.5,Adult,Male,28-01-2015,Venezuela,Mangroves,Vulnerable,Brandon Hall,Ago current practice nation determine operatio...
2,3,Orinoco Crocodile,Crocodylus intermedius,Crocodylidae,Crocodylus,1.08,118.2,Juvenile,Unknown,07-12-2010,Venezuela,Flooded Savannas,Critically Endangered,Melissa Peterson,Democratic shake bill here grow gas enough ana...
3,4,Morelet's Crocodile,Crocodylus moreletii,Crocodylidae,Crocodylus,2.42,90.4,Adult,Male,01-11-2019,Mexico,Rivers,Least Concern,Edward Fuller,Officer relate animal direction eye bag do.
4,5,Mugger Crocodile (Marsh Crocodile),Crocodylus palustris,Crocodylidae,Crocodylus,3.75,269.4,Adult,Unknown,15-07-2019,India,Rivers,Vulnerable,Donald Reid,Class great prove reduce raise author play mov...

In [143]:
df2=df2.drop(columns=["Observation ID","Common Name","Scientific Name","Family",	"Genus","Age Class","Date of Observation","Country/Region","Habitat Type","Observer Name",	"Notes"])

In [144]:
df2.head()

   Observed Length (m)  Observed Weight (kg)      Sex    Conservation Status
0                 1.90                  62.0     Male          Least Concern
1                 4.09                 334.5     Male             Vulnerable
2                 1.08                 118.2  Unknown  Critically Endangered
3                 2.42                  90.4     Male          Least Concern
4                 3.75                 269.4  Unknown             Vulnerable

In [145]:
from sklearn.preprocessing import LabelEncoder

In [146]:
lb=LabelEncoder()

In [147]:
df2["Sex"]=lb.fit_transform(df2["Sex"])

In [148]:
x=df2.drop(columns=["Conservation Status"])
y=df2["Conservation Status"]

In [149]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [150]:
x_train.head()

     Observed Length (m)  Observed Weight (kg)  Sex
29                  4.71                 576.6    0
535                 3.96                 385.8    1
695                 1.68                  45.9    0
557                 3.10                 156.3    0
836                 2.35                  84.2    0

In [151]:
sc=StandardScaler()

In [153]:
x_train_sc=sc.fit_transform(x_train)

In [161]:
x_train_new=pd.DataFrame(x_train_sc,columns=x.columns)

In [162]:
np.round(x_train_new.describe(),2)

       Observed Length (m)  Observed Weight (kg)     Sex
count               800.00                800.00  800.00
mean                 -0.00                  0.00   -0.00
std                   1.00                  1.00    1.00
min                  -2.08                 -0.87   -1.29
25%                  -0.71                 -0.59   -1.29
50%                   0.01                 -0.33   -0.06
75%                   0.53                  0.11    1.16
max                   3.35                  5.49    1.16

In [157]:
print("----------------------------------------------------------------------")

----------------------------------------------------------------------

In [179]:
df3=pd.read_csv("ai_dev_productivity - ai_dev_productivity.csv")

In [180]:
df3.head()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
0,5.99,600,1,5.8,2,1,0.71,5.4,1
1,4.72,568,2,6.9,5,3,1.75,4.7,1
2,6.30,560,1,8.9,2,0,2.27,2.2,1
3,8.05,600,7,6.3,9,5,1.40,5.9,0
4,4.53,421,6,6.9,4,0,1.26,6.3,1

In [181]:
x=df3.drop(columns=["task_success"])
y=df3["task_success"]

In [183]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [184]:
x_train.describe()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load
count,400.000000,400.000000,400.000000,400.00000,400.000000,400.000000,400.000000,400.000000
mean,5.006600,460.650000,2.947500,6.98275,4.605000,0.865000,1.466025,4.472000
std,1.961409,144.527222,1.681312,1.48649,2.705045,1.108986,1.063049,1.918075
min,0.000000,6.000000,0.000000,3.00000,0.000000,0.000000,0.000000,1.000000
25%,3.560000,366.000000,2.000000,6.10000,3.000000,0.000000,0.660000,3.100000
50%,5.010000,498.000000,3.000000,6.90000,5.000000,0.000000,1.235000,4.400000
75%,6.312500,600.000000,4.000000,7.90000,6.000000,2.000000,1.990000,5.900000
max,11.160000,600.000000,8.000000,10.00000,13.000000,5.000000,6.360000,10.000000

In [186]:
from sklearn.preprocessing import MinMaxScaler

In [187]:
mn=MinMaxScaler()

In [188]:
x_train_mn=mn.fit_transform(x_train)

In [189]:
type(x_train_mn)

numpy.ndarray

In [197]:
x_train_new=pd.DataFrame(x_train_mn,columns=x.columns)

In [198]:
x_train_new.describe()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,0.448620,0.765404,0.368437,0.568964,0.354231,0.173000,0.230507,0.385778
std,0.175753,0.243312,0.210164,0.212356,0.208080,0.221797,0.167146,0.213119
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.318996,0.606061,0.250000,0.442857,0.230769,0.000000,0.103774,0.233333
50%,0.448925,0.828283,0.375000,0.557143,0.384615,0.000000,0.194182,0.377778
75%,0.565636,1.000000,0.500000,0.700000,0.461538,0.400000,0.312893,0.544444
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000